accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/and/register/", views.login_and_register_view, name="login-register"),
    path("logout/", views.logout_view, name="logout"),
    path("activation/complete/<uuid>/<token>/", views.activation_view_complete, name="activation"),
    path("reset/password/", views.reset_password_view, name="reset-password"),
    path("reset/password/complete/<uuid>/<token>/", views.reset_password_complete, name="reset_password_complete")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("products.urls")),
    path("accounts/", include("accounts.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("vacancy/", views.vacancies_view, name="vacancies"),
    path("faq/", views.faq_view, name="faq"),
    path("contact/", views.contact_us_view, name="contact-us"),
    path("shop/", views.shop_view, name="shop"),
]

accounts/models.py
from django.db import models
from services.generator import CodeGenerator
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)


class MyUserManager(BaseUserManager):
    def create_user(
        self,
        email,
        name,
        surname,
        password=None,
        is_active=True,
        is_staff=False,
        is_superuser=False
    ):
        if not email:
            raise ValueError("Users must have an email address")
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.name = name
        user.surname = surname
        user.is_active = is_active
        user.is_staff = is_staff
        user.is_superuser = is_superuser
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name=None, surname=None, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            name=name,
            surname=surname,
            password=password,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


def upload_to(instance, filename):
    return f"users/{instance.email}/{filename}"


class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=120)
    name = models.CharField(max_length=250, blank=True, null=True)
    surname = models.CharField(max_length=250, blank=True, null=True)
    logo = models.ImageField(upload_to=upload_to, blank=True, null=True)

    slug = models.SlugField(unique=True)
    activation_code = models.CharField(max_length=6, blank=True, null=True)

    timestamp = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "email"

    class Meta:
        ordering = ["-timestamp"]
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.email

    def full_name(self):
        return f"{self.name} {self.surname}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = CodeGenerator.create_slug_shortcode(size=20, model_=MyUser)
        return super(MyUser, self).save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField


User = get_user_model()

# -----------------------   Admin Forms  ---------------------------------------------------


class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = [
            "email",
            "name",
            "surname",
            "password1",
            "password2",
        ]

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            self.add_error("password1","Şifrələr arasında ziddiyyət var.")
        return password2

    def save(self, commit=True):
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = [
            "email",
            "name",
            "surname",
            "is_active",
            "is_staff",
            "is_superuser",
            "password",
        ]

    def clean_password(self):
        return self.initial["password"]


class LoginForm(forms.ModelForm):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("email", "password")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields:
            self.fields[filed].widget.attrs.update({"class": "form-control", "placeholder": filed.title})

    def get_user(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        return authenticate(email=email, password=password)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        try:
            user = User.objects.get(email=email)
        except:
            raise forms.ValidationError("No account with this email.")

        if not user.check_password(password):
            raise forms.ValidationError("Password is wrong.")

        if not user.is_active:
            raise forms.ValidationError("This account is not activate.")

        return self.cleaned_data


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("email", "name", "surname", "password", "password_confirm")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {"name": "Name", "surname": "Surname", "email": "Email", "password": "Password", "password_confirm": "Password confirm"}
        for filed in self.fields:
            self.fields[filed].widget.attrs.update({"class": "form-control", "placeholder": placeholders[filed]})

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email already exists.")
        if len(password) < 8:
            raise forms.ValidationError("Password should contain 8 character at least.")
        if not any(i.isdigit() for i in password):
            raise forms.ValidationError("The password must contain at least 1 number and letters.")
        if password != password_confirm:
            raise forms.ValidationError("Passwords should match.")
        return self.cleaned_data

    def save(self, commit=True):
        password = self.cleaned_data.pop("password_confirm")

        user = User.objects.create(
            **self.cleaned_data, is_active=False
        )
        user.set_password(password)
        user.save()
        return user


class ResetPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email", )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({"class": "form-control", "placeholder": "enter you mail"})

    def clean(self):
        email = self.cleaned_data.get("email")

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email does not exist.")
        return self.cleaned_data


class ResetPasswordComplete(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("password", "password_confirm")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {"password": "Password", "password_confirm": "Password confirm"}
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "placeholder": placeholders[field]})

    def clean(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise forms.ValidationError("Passwords didn't match.")

        if len(password_confirm) <= 7:
            raise forms.ValidationError("Password length must be at least 8.")

        if not any(i.isdigit() for i in password_confirm):
            raise forms.ValidationError("The password must contain at least 1 number and letters.")

        if self.instance.check_password(password_confirm):
            raise forms.ValidationError("You can't use the old password.")

        return self.cleaned_data

    def save(self):
        password = self.cleaned_data.get("password")
        self.instance.set_password(password)
        self.instance.save()
        return self.instance

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, get_user_model
from .forms import LoginForm, RegisterForm, ResetPasswordForm, ResetPasswordComplete
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import smart_str, smart_bytes
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib import messages

User = get_user_model()


def login_and_register_view(request):
    login_form = LoginForm()
    register_form = RegisterForm()

    if request.method == "POST":
        submit = request.POST.get("submit")
        if submit == "login_form":
            login_form = LoginForm(request.POST or None)
            if login_form.is_valid():
                user = login_form.get_user()
                login(request, user)
                return redirect("/")
        else:
            register_form = RegisterForm(request.POST or None)
            if register_form.is_valid():
                new_user = register_form.save()
                uuid = urlsafe_base64_encode(smart_bytes(new_user.slug))
                token = PasswordResetTokenGenerator().make_token(new_user)
                link = request.build_absolute_uri(reverse_lazy("accounts:activation", kwargs={"uuid": uuid, "token": token}))
                send_mail(
                    "Electronics\n",
                    f"Linke kecid edib hesabinizi aktivlesdirin\n{link}",
                    settings.EMAIL_HOST_USER,
                    [new_user.email],
                    fail_silently=True
                )
                return redirect("/")
    context = {
        "login_form": login_form,
        "register_form": register_form
    }
    return render(request, "accounts/login_and_register.html", context)


def logout_view(request):
    logout(request)
    return redirect("/")


def activation_view_complete(request, uuid, token):
    slug = smart_str(urlsafe_base64_decode(uuid))
    user = User.objects.get(slug=slug)

    if not PasswordResetTokenGenerator().check_token(user, token):
        message = "Link duzgun deil!"
        messages.error(request, message)
        return redirect("accounts:login")
    user.is_active=True
    user.save()
    return redirect("/")


def reset_password_view(request):
    form = ResetPasswordForm()

    if request.method == "POST":
        form = ResetPasswordForm(request.POST or None)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            user = get_object_or_404(User, email=email)
            uuid = urlsafe_base64_encode(smart_bytes(user.slug))
            token = PasswordResetTokenGenerator().make_token(user)
            link = request.build_absolute_uri(reverse_lazy("accounts:reset_password_complete", kwargs={"uuid": uuid, "token": token}))
            send_mail(
                "Reset Password",
                f"Please click link the bellow\n{link}",
                settings.EMAIL_HOST_USER,
                [email],
                fail_silently=True
            )
            return redirect("/")
    context = {"form": form}
    return render(request, "accounts/reset_password.html", context)


def reset_password_complete(request, uuid, token):
    slug = smart_str(urlsafe_base64_decode(uuid))
    user = get_object_or_404(User, slug=slug)
    form = ResetPasswordComplete(instance=user)

    if not PasswordResetTokenGenerator().check_token(user, token):
        message = "Link duzgun deil!"
        messages.error(request, message)
        return redirect("accounts:login")

    if request.method == "POST":
        form = ResetPasswordComplete(instance=user, data=request.POST or None)

        if form.is_valid():
            form.save()
            return redirect("accounts:login-register")

    context = {"form": form}
    return render(request, "accounts/reset_password_complete.html", context)

templates/accounts/reset_password.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
        <!-- offcanvas overlay start -->
        <div class="offcanvas-overlay"></div>
        <div id="offcanvas-mobile-menu" class="offcanvas offcanvas-mobile-menu">
            <button class="offcanvas-close"></button>
            <div class="user-panel">
            </div>
            <div class="inner customScroll">
            </div>
        </div>
        <!-- OffCanvas Menu End -->
        <!-- breadcrumb-area start -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-12 text-center">
                        <h1>Reset password</h1>
                        <!-- breadcrumb-list start -->
                        <ul class="breadcrumb-list">
                            <li class="breadcrumb-item"><a href="{% url 'products:index' %}">Home</a></li>
                            <li class="breadcrumb-item active">Reset password</li>
                        </ul>
                        <!-- breadcrumb-list end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb-area end -->
        <!-- login area start -->
        <div class="login-register-area pt-100px pb-100px">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                        <div class="login-register-wrapper">
                            <div class="login-register-tab-list nav">
                                <a class="active" data-bs-toggle="tab" href="#lg1" onclick="setLastForm('lg1')">
                                    <h4>Reset password</h4>
                                </a>
                            </div>
                            <div class="tab-content">
                                <div id="lg1" class="tab-pane active">
                                    <div class="login-form-container">
                                        <div class="login-register-form">
                                            <form method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="submit" value="login_form">
                                                {% if form.errors %}
                                                        {% for error in form.non_field_errors %}
                                                        <ul>
                                                            <li style="color:DodgerBlue;">{{ error }}</li>
                                                        </ul>
                                                        {% endfor %}
                                                {% endif %}
                                                    {{form.email}}
                                                <div class="button-box">
                                                    <button type="submit"><span>Send mail</span></button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/accounts/reset_password_complete.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
        <!-- offcanvas overlay start -->
        <div class="offcanvas-overlay"></div>
        <div id="offcanvas-mobile-menu" class="offcanvas offcanvas-mobile-menu">
            <button class="offcanvas-close"></button>
            <div class="user-panel">
            </div>
            <div class="inner customScroll">
            </div>
        </div>
        <!-- OffCanvas Menu End -->
        <!-- breadcrumb-area start -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-12 text-center">
                        <h1>Reset password</h1>
                        <!-- breadcrumb-list start -->
                        <ul class="breadcrumb-list">
                            <li class="breadcrumb-item"><a href="{% url 'products:index' %}">Home</a></li>
                            <li class="breadcrumb-item active">Reset password</li>
                        </ul>
                        <!-- breadcrumb-list end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb-area end -->
        <!-- login area start -->
        <div class="login-register-area pt-100px pb-100px">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                        <div class="login-register-wrapper">
                            <div class="login-register-tab-list nav">
                                <a class="active" data-bs-toggle="tab" href="#lg1" onclick="setLastForm('lg1')">
                                    <h4>Reset password</h4>
                                </a>
                            </div>
                            <div class="tab-content">
                                <div id="lg1" class="tab-pane active">
                                    <div class="login-form-container">
                                        <div class="login-register-form">
                                            <form method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="submit" value="login_form">
                                                {% if form.errors %}
                                                        {% for error in form.non_field_errors %}
                                                        <ul>
                                                            <li style="color:DodgerBlue;">{{ error }}</li>
                                                        </ul>
                                                        {% endfor %}
                                                {% endif %}
                                                {% for field in form %}
                                                    {{field}}
                                                {% endfor %}
                                                <div class="button-box">
                                                    <button type="submit"><span>Save</span></button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}